service: myservice
app: sumanta-test
org: dataminr
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  addTask:
    handler: .build/src/commands/addTask.handler
    events:
      - http: 'POST /addTask'
  addList:
    handler: .build/src/commands/addList.handler
    events:
      - http: 'POST /addList'
  addTaskList:
    handler: .build/src/commands/addTaskList.handler
    events:
      - http: 'POST /addTaskList'
